version: "3"
services:

  # Put traces in a Grafana Agent pipeline...
  agent:
    image: grafana/agent:v0.29.0
    volumes:
      - ./agent/agent.yaml:/etc/agent.yaml
    entrypoint:
     - /bin/agent
     - -config.file=/etc/agent.yaml
    ports:
     - "4317:4317"   # otlp grpc
     - "4318:4318"   # otlp http

  # To eventually offload to Tempo...
  tempo:
    image: grafana/tempo:main-81aa300-arm64
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    ports:
      - "3200:3200"    # tempo
      - "4317"         # otlp grpc
      - "4318"         # otlp http

  prometheus:
    image: prom/prometheus:v2.40.7
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./shared/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:9.3.2
    volumes:
      - ./shared/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=tempoApmTable
    ports:
      - "3000:3000"